version: '2'

volumes:
  db03:
  app03:

services:
  mariadb:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db03:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    container_name: nextcloud-app
    hostname: nextcloud
    restart: always
    ports:
      - 8888:80
    links:
      - mariadb
    volumes:
      - app03:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
      - OVERWRITECLIURL=${URL}
      - OVERWRITEPROTOCOL=https
      - APACHE_DISABLE_REWRITE_IP=1
