version: "2.1"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    network_mode: 'host'
    volumes:
      - /root/jellyfin/jellyfin_config:/config
      - /root/jellyfin/jellyfin_cache:/cache
      - /root/jellyfin/media:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://music.manuelselch.de

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /root/jellyfin/media:/media
      - /root/jellyfin/downloads:/downloads
      - /root/jellyfin/lidarr_config:/config      
    ports:
      - 8686:8686
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8082
    volumes:
      - /root/jellyfin/qbittorrent_config:/config
      - /root/jellyfin/downloads:/downloads
    ports:
      - 8082:8082
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /root/jellyfin/jackett_config:/config
      - /root/jellyfin/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
